apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
spec:
  descriptor:
    type: SDK
    version: "{{ .Values.global.azure.images.tdkoffer.registry }}"
    description: |-
      Populate non-production environments with production-like data.
    maintainers:
      - name: Synthesized
        url: https://www.synthesized.io/
    notes: |-
      You can learn more about TDK by clicking on the link - https://docs.synthesized.io/tdk/latest/user_guide/getting_started/what_is_tdk
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  addOwnerRef: true
  componentKinds:
    - group: v1
      kind: Secret
    - group: batch/v1
      kind: CronJob
    - group: batch/v1
      kind: Job
    - group: apps/v1
      kind: Deployment
    - group: v1
      kind: ServiceAccount
